version: '2'
services:
  parser:
    build:
      context: .
      dockerfile: docker/Dockerfile-parser
    #command: bash -c  "go run *.go"
    volumes:
      - ./parser:/go/src/parser
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
